<?php
/**
 * @file
 * UCMS - Site context and management.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\Select;
use Drupal\Core\Entity\EntityTypeInterface;
use MakinaCorpus\Ucms\Site\Access;
use MakinaCorpus\Ucms\Site\Environment\NodeDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function ucms_site_entity_base_field_info(EntityTypeInterface $entity_type) {
  switch ($entity_type->id()) {

    case 'node':
      return NodeDefinition::getAdditionalBaseFields();
  }
}

/**
 * Implements hook_menu().
 *
function ucms_site_menu() {
  $items = [];

  $items['admin/dashboard/site/archive'] = [
    'title'             => "Archives",
    'page callback'     => 'ucms_site_dashboard_site_list_archive',
    'access arguments'  => [Access::PERM_SITE_DASHBOARD_ACCESS],
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 100,
    'file'              => 'ucms_site.dashboard.inc',
  ];
  if (module_exists('ucms_notification')) {
    $items['admin/dashboard/site/%ucms_site/log'] = [
      'title'             => "Log",
      'page callback'     => 'ucms_site_dashboard_site_page_log',
      'page arguments'    => [3],
      'access callback'   => 'ucms_site_menu_access_overview',
      'access arguments'  => [3],
      'type'              => MENU_LOCAL_TASK,
      'file'              => 'ucms_site.dashboard.inc',
    ];
  }
  $items['admin/dashboard/site/%ucms_site/delete'] = [
    'title'             => "Site delete",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\SiteDelete', 3],
    'access callback'   => 'ucms_site_menu_access_manage',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/site/%ucms_site/webmaster/add-new'] = [
    'title'             => "Create a new webmaster or contributor",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\WebmasterAddNew', 3],
    'access callback'   => 'ucms_site_menu_access_webmasters',
    'access arguments'  => ['add-new', 3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/site/%ucms_site/webmaster/%user/promote'] = [
    'title'             => "Promote as webmaster",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\WebmasterPromote', 3, 5],
    'access callback'   => 'ucms_site_menu_access_webmasters',
    'access arguments'  => ['promote', 3, 5],
    'type'              => MENU_CALLBACK,
  ];
  $items['admin/dashboard/site/%ucms_site/webmaster/%user/demote'] = [
    'title'             => "Demote as contributor",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\WebmasterDemote', 3, 5],
    'access callback'   => 'ucms_site_menu_access_webmasters',
    'access arguments'  => ['demote', 3, 5],
    'type'              => MENU_CALLBACK,
  ];

  $items['admin/dashboard/ajax/sites-ac'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [AutocompleteController::class . '::siteAutocompleteAction'],
    'type'              => MENU_CALLBACK,
  ];

  $items['node/%node/reference'] = [
    'title'             => "Reference this content",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\NodeReference', 1],
    'access callback'   => 'ucms_site_menu_access_reference',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['node/%node/dereference-from/%ucms_site'] = [
    'title'             => "Dereference this content from current site",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\NodeDereferenceFrom', 1, 3],
    'access callback'   => 'ucms_site_menu_access_dereference_from',
    'access arguments'  => [1, 3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['node/%node/set-home'] = [
    'title'             => "Set as home page",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Form\NodeSetHome', 1],
    'access callback'   => 'ucms_site_menu_access_manage_current',
    'access arguments'  => [],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  $items['node/%node/site-list'] = [
    'title'             => "Sites",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => ['MakinaCorpus\Ucms\Site\Controller\NodeInfoController::siteList', 1],
    'access callback'   => 'node_access',
    'access arguments'  => ['view', 1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  return $items;
}
 */

/**
 * Implements hook_drupal_goto_alter().
 *
function ucms_site_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  if (ucms_site_is_master()) {
    $matches = [];
    if (module_exists('ucms_sso') && preg_match('@^node/(\d+)(|/(view|edit))?$@', $path, $matches)) {
      $node = \Drupal::service('entity.manager')->getStorage('node')->load($matches[1]);
      if (!empty($node->site_id)) {
        $options['query'] = ['destination' => $path];
        $path = 'sso/goto/' . $node->site_id;
      }
    }
  }
}
 */

/**
 * Get site manager service.
 *
 * @return \MakinaCorpus\Ucms\Site\SiteManager
 */
function ucms_site_manager() {
  return \Drupal::service('ucms_site.manager');
}

/**
 * Get node access helper.
 *
 * @return \MakinaCorpus\Ucms\Site\NodeAccessService
 */
function ucms_site_node_access_helper() {
  return \Drupal::service('ucms_site.node_access_helper');
}

/**
 * Menu helper.
 */
function ucms_site_load($id) {
  try {
    return ucms_site_manager()->getStorage()->findOne($id);
  } catch (\InvalidArgumentException $e) {
    return false;
  }
}

/**
 * Menu helper.
 *
function ucms_site_menu_access_view_all($account = null) {
  if (!$account) {
    $account = \Drupal::currentUser();
  }
  return
    $account->hasPermission(Access::PERM_SITE_MANAGE_ALL) ||
    $account->hasPermission(Access::PERM_SITE_VIEW_ALL) ||
    $account->hasPermission(Access::PERM_SITE_GOD)
  ;
}
 */

/**
 * Menu access check helper.
 *
 * @param string $op The operation the user wanna perform
 * @param Site $site
 * @param AccountInterface $webmaster
 * @param AccountInterface $account
 *
 * @return boolean
 *
function ucms_site_menu_access_webmasters($op, Site $site, AccountInterface $webmaster = null, AccountInterface $account = null) {
  if (!$account) {
    $account = \Drupal::currentUser();
  }

  $manager = ucms_site_manager();

  if ($manager->getAccess()->userCanManageWebmasters($account, $site)) {
    switch ($op) {
      case 'change-role':
        // Prevents to give a role to a user which doesn't belong to the site
        if (!$manager->getAccess()->userHasRole($webmaster, $site)) {
          return false;
        }
        break;

      case 'promote':
        // Prevents to promote a user which is not a contributor of the site
        if (!$manager->getAccess()->userIsContributor($webmaster, $site)) {
          return false;
        }
        break;

      case 'demote':
        // Prevents to demote a user which is not a webmaster of the site
        if (!$manager->getAccess()->userIsWebmaster($webmaster, $site)) {
          return false;
        }
        break;
    }

    return true;
  }

  return false;
}
 */

/**
 * Menu access check helper.
 *
function ucms_site_menu_access_reference(NodeInterface $node, $account = null) {
  if (!$account) {
    $account = \Drupal::currentUser();
  }
  return $node->access('view', $account) && ucms_site_node_access_helper()->userCanReference($account, $node);
}
 */

/**
 * Menu access check helper.
 *
function ucms_site_menu_access_dereference_from(NodeInterface $node, $site = null, $account = null) {
  if (!$account) {
    $account = \Drupal::currentUser();
  }
  $manager = ucms_site_manager();
  if (!$site) {
    if (!$manager->hasContext()) {
      return false;
    }
    $site = $manager->getContext();
  }
  return ucms_site_node_access_helper()->userCanDereference($account, $node, $site);
}
 */

/**
 * Implements hook_file_url_alter().
 */
function ucms_site_file_url_alter(&$uri) {
  $scheme = file_uri_scheme($uri);

  // When there is no scheme, this means we are dealing with core or module
  // packaged files, such as static JS or CSS files.
  if ($scheme && 'public' !== $scheme) {
    return;
  }

  /** @var \MakinaCorpus\Ucms\Site\SiteManager $manager */
  $manager = \Drupal::service('ucms_site.manager');

  if (!$hostname = $manager->getCdnUrl()) {
    return; // Misconfigured parameter.
  }

  if (!$scheme) {
    // Module or core packaged files.
    $path = $uri;
  } else {
    // This code comes from the official documentation.
    $wrapper = \Drupal::service('stream_wrapper_manager')->getViaScheme($scheme);
    $path = $wrapper->getDirectoryPath().'/'.file_uri_target($uri);
  }

  // Clean up Windows paths.
  $path = str_replace('\\', '/', $path);

  $uri = $hostname.'/'.$path;
}

/**
 * Redirect on node view if node can be viewed elsewhere than master.
 * /
function ucms_site_init_node_redirect() {
  if (user_is_anonymous()) { // Better be safe than sorry.
    return;
  }
  if (!ucms_site_is_master()) { // Non-applicable.
    return;
  }
  // Pure optimisation, and find node view page at the same time.
  if ('node' !== arg(0) || !is_numeric(arg(1)) || arg(2)) {
    return;
  }
  if ($node = menu_get_object()) {
    // findMostRelevantSiteFor() allows fetching URL for non enabled sites, but
    // will always find a site the current user can see. This function will
    // always be called when attempting to connect on the admin sites, so this
    // fine to redirect on non enabled sites if no enabled site was found.
    $siteId = ucms_site_node_access_helper()->findMostRelevantSiteFor($node);
    if ($siteId) {
      drupal_goto('sso/goto/' . $siteId, ['query' => ['destination' => current_path()]]);
    }
  }
}
 */

/**
 * Implements hook_init().
 * /
function ucms_site_init() {

  if (drupal_is_cli()) {
    return; // Make drush happy.
  }

  $manager = ucms_site_manager();

  // We might have some problems due to the fact that the site is determined
  // at hook_boot() time, for example, we cannot call the path_is_admin()
  // function because modules have not been invoked. Site is being set way
  // before at hook_boot() in order to ensure that everything actually using
  // this information until now does it right (they should only be revelant
  // for frontend anyway), but we have a chance right now to fix admin paths
  // and remove the site information right now.
  if ($manager->hasContext()) {
    // We avoid redirections on dashboard in case of POST requests
    // to allow layout management requests (AJAX)
    if (!ucms_site_admin_path_is_allowed(current_path())) {
      if (user_is_logged_in()) {
        // Logged-in users should not 403 on sites, but go to dashboard instead.
        ucms_site_redirect_to_master();
      }
    }
  } else if (user_is_logged_in() && !ucms_site_is_master()) {
    ucms_site_redirect_to_master(); // Site does not exists.
  }

  ucms_site_init_node_redirect();
}
 */

/**
 * Implements hook_query_TAG_alter().
 *
 * This is required in order for users that may bypass node access (UID 1 is
 * one of them) to have site content correctly isolated depending on context.
 */
function ucms_site_query_node_access_alter(AlterableInterface $query) {
  $siteManager = ucms_site_manager();

  if (!$siteManager->hasContext() || $query->hasTag(Access::QUERY_TAG_CONTEXT_OPT_OUT) || !$query instanceof Select) {
    return;
  }

  // If no base table is specified explicitly, search for one.
  if (!$nodeAlias = $query->getMetaData('base_table')) {
    foreach ($query->getTables() as $alias => $table_info) {
      if (!($table_info instanceof Select)) {
        // If the node table is in the query, it wins immediately.
        $table = $table_info['table'];
        if ('node' === $table || 'node_field_data' === $table) {
          $nodeAlias = $alias;
          // Ensure that 'node' and 'node_field_data' are prefered over revisions.
          break;
        }
        if ('node_revision' === $table || 'node_field_revision' === $table) {
          $nodeAlias = $alias;
        }
      }
    }
  }

  // There's no table to join.
  if (!$nodeAlias) {
    return;
  }

  // Where the magic happens.
  $query->join('ucms_site_node', 'access_sn',
    "access_sn.nid = " . $nodeAlias . ".nid AND access_sn.site_id = :access_sn_site_id",
    [':access_sn_site_id' => $siteManager->getContext()->getId()]
  );
}

/**
 * Implements hook_query_TAG_alter().
 *
 * Implement site visibility access control for the admin UI, this is the only
 * query alteration for business purpose this module will ever do.
 *
function ucms_site_query_ucms_site_access_alter(QueryAlterableInterface $query) {

  if (!$query instanceof SelectQueryInterface) {
    return;
  }
  if (drupal_is_cli()) {
    // In theory, we should not have to do this, but it happens that during
    // drush upgrade, which runs all update functions altogether one by one,
    // it may happen that this module gets enable during the same run, and
    // that the 'sf_dic' container, even if correctly rebuilt, may not be
    // used because older object references are being used by the code (old
    // services still referenced into some other being in use).
    return;
  }

  /* @var $account AccountInterface * /
  if (!$account = $query->getMetaData('account')) {
    $account = \Drupal::currentUser();
  }

  if ($account->hasPermission(Access::PERM_SITE_GOD) ||
      $account->hasPermission(Access::PERM_SITE_MANAGE_ALL) ||
      $account->hasPermission(Access::PERM_SITE_VIEW_ALL)
  ) {
    return;
  }

  /** @var \MakinaCorpus\Ucms\Site\GroupManager $groupManager * /
  $groupManager = \Drupal::service('ucms_group.manager');
  $accessList   = $groupManager->getUserGroups($account);
  $siteAlias    = null;
  $accessAlias  = null;

  // If no base table is specified explicitly, search for one.
  foreach ($query->getTables() as $alias => $table_info) {
    if (!($table_info instanceof SelectQueryInterface)) {
      // If the node table is in the query, it wins immediately.
      if ('ucms_site' === $table_info['table']) {
        $siteAlias = $alias;
      }
      if ('ucms_site_access' === $table_info['table']) {
        $accessAlias = $alias;
      }
    }
  }

  if (!$siteAlias && !$accessAlias) {
    return;
  }

  // Apply group conditions, but do not apply anything if the user is not
  // member of any groups: it means that the user is a global administrator.
  if ($accessList) {
    if (!$siteAlias) {
      $siteAlias = $query->join(
        'ucms_site',
        'access_site',
        "access_site.id = " . $accessAlias . ".site_id"
      );
    }
    $groupList = [];
    foreach ($accessList as $access) {
      $groupList[] = $access->getGroupId();
    }
    $query->condition($siteAlias . '.group_id', $groupList);
  }

  // Apply normal user permissions if the current user cannot see all sites
  if (!$account->hasPermission(Access::PERM_SITE_MANAGE_ALL) && !$account->hasPermission(Access::PERM_SITE_VIEW_ALL)) {
    if (!$accessAlias) {
      $query->join(
        'ucms_site_access',
        'access_sa',
        "access_sa.site_id = " . $siteAlias . ".id AND access_sa.uid = :access_sa_uid",
        [':access_sa_uid' => $account->id()]
      );
    } else {
      $query->condition($accessAlias . '.uid', $account->id());
    }
  }
}
 */

/**
 * Implements hook_query_TAG_alter().
 *
 * Implement site visibility access control for the admin UI, this is the only
 * query alteration for business purpose this module will ever do.
 *
function ucms_site_query_ucms_user_access_alter(QueryAlterableInterface $query) {

  if (!$query instanceof SelectQueryInterface) {
    return;
  }
  if (drupal_is_cli()) {
    // In theory, we should not have to do this, but it happens that during
    // drush upgrade, which runs all update functions altogether one by one,
    // it may happen that this module gets enable during the same run, and
    // that the 'sf_dic' container, even if correctly rebuilt, may not be
    // used because older object references are being used by the code (old
    // services still referenced into some other being in use).
    return;
  }

  /* @var $account AccountInterface * /
  if (!$account = $query->getMetaData('account')) {
    $account = \Drupal::currentUser();
  }

  if ($account->hasPermission(Access::PERM_USER_MANAGE_ALL) || $account->hasPermission(Access::PERM_USER_VIEW_ALL)) {
    return;
  }

  $userAlias = null;
  $userGroupAlias = null;

  // If no base table is specified explicitly, search for one.
  foreach ($query->getTables() as $alias => $table_info) {
    if (!($table_info instanceof SelectQueryInterface)) {
      // If the node table is in the query, it wins immediately.
      if ('users' === $table_info['table']) {
        $userAlias = $alias;
      }
      if ('ucms_group_access' === $table_info['table']) {
        $userGroupAlias = $alias;
      }
    }
  }

  if (!$userAlias) {
    return;
  }

  /** @var \MakinaCorpus\Ucms\Site\GroupManager $groupManager * /
  $groupManager = \Drupal::service('ucms_group.manager');
  $accessList   = $groupManager->getUserGroups($account);

  // Group admins can view users from their own groups, at least in listings.
  // But more than that, can ONLY see users from their groups.
  if ($accessList) {
    $groupList = [];
    foreach ($accessList as $access) {
      $groupList[] = $access->getGroupId();
    }
    if (!$userGroupAlias) {
      $userGroupAlias = $query->join('ucms_group_access', 'uga', "uga.user_id = " . $userAlias . '.uid');
    }
    $query->condition($userGroupAlias . '.group_id', $groupList);
  } else {
    $query->where("1 = 0"); // You fool.
  }
}
 */

/**
 * Implements hook_taxonomy_term_presave().
 *
function ucms_site_taxonomy_term_presave($term) {
  // Maintain term creators.
  if (empty($term->original) && !empty($GLOBALS['user']->uid)) {
    $term->user_id = $GLOBALS['user']->uid;
  }
}
 */

/**
 * Render the state transition form.
 *
function theme_ucms_site_state_transition_form($variables) {
  $form = $variables['form'];

  $header = [''];
  $rows   = [];
  $map    = SiteState::getList();

  foreach (element_children($form['transitions']) as $k1) {
    $header[] = t($map[$k1]);
    $row = [];
    $row[] = ['data' => $map[$k1], 'header' => true];
    foreach (element_children($form['transitions'][$k1]) as $k2) {
      if ($k1 != $k2) {
        $row[] = drupal_render_children($form['transitions'][$k1][$k2]);
      } else {
        $row[] = ['data' => '<span class="text-muted">' . t("N/A") . '</span>', 'style' => 'text-align: center;'];
      }
    }
    $rows[] = $row;
  }

  return theme('table', ['header' => $header, 'rows' => $rows]) . drupal_render_children($form);
}
 */

/**
 * Implements hook_image_default_styles()
 *
 * @todo https://www.drupal.org/docs/8/theming-drupal-8/including-default-image-styles-with-your-theme
 *
function ucms_site_image_default_styles() {
  $styles = [];
  $styles['ucms_site_favicon_32x32'] = [
    'label' => 'Favicon 32x32px',
    'effects' => [
      [
        'name' => 'image_scale',
        'data' => [
          'width' => 32,
          'height' => 32,
        ],
        'weight' => 0,
      ],
    ],
    'name' => 'ucms_favicon_32x32',
    'storage' => IMAGE_STORAGE_DEFAULT,
  ];
  $styles['ucms_site_favicon_16x16'] = [
    'label' => 'Favicon 16x16px',
    'effects' => [
      [
        'name' => 'image_scale',
        'data' => [
          'width' => 16,
          'height' => 16,
        ],
        'weight' => 0,
      ],
    ],
    'name' => 'ucms_favicon_16x16',
    'storage' => IMAGE_STORAGE_DEFAULT,
  ];

  return $styles;
}
 */

/**
 * Implements hook_page_build()
 *
function ucms_site_page_build(&$page) {
  $manager = ucms_site_manager();

  if ($manager->hasContext()) {
    $site = $manager->getContext();

    // Handling custom favicon
    if ($favicon = $site->getFavicon()) {
      if ($file = file_load($favicon)) {
        $element = [
          '#tag' => 'link',
          '#attributes' => [
            'href'  => image_style_url('ucms_site_favicon_32x32', $file->uri),
            'rel'   => 'icon',
            'sizes' => "32x32"
          ],
        ];
        drupal_add_html_head($element, 'ucms_site_favicon_32x32');

        $element = [
          '#tag' => 'link',
          '#attributes' => [
            'href'  => image_style_url('ucms_site_favicon_16x16', $file->uri),
            'rel'   => 'icon',
            'sizes' => "16x16"
          ],
        ];
        drupal_add_html_head($element, 'ucms_site_favicon_16x16');
      }
    }
  }
}
 */

