<?php
/**
 * @file
 * UCMS Tree module.
 */

use MakinaCorpus\Umenu\Menu;

/**
 * Implements hook_menu().
 */
function ucms_tree_menu() {
  $items = [];

  // @todo this one is wrong
  $items['admin/dashboard/tree'] = [
    'title'           => 'Tree',
    'page callback'   => 'sf_dic_page_form',
    'page arguments'  => ['MakinaCorpus\Ucms\Tree\Form\TreeForm'],
    'access callback' => 'ucms_tree_check_access_admin',
    'type'            => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/tree-list'] = [
    'title'             => "All tress",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => ['MakinaCorpus\Ucms\Tree\Controller\TreeAdmin::treeList', 1],
    'access callback'   => 'ucms_tree_check_access_admin',
    'type'              => MENU_NORMAL_ITEM,
  ];
  $items['admin/dashboard/tree/add'] = [
    'title'             => 'Add new menu',
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Tree\Form\TreeEditForm'],
    'access callback'   => 'ucms_tree_check_access_create',
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/tree/%umenu/edit'] = [
    'title'             => 'Edit menu',
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Tree\Form\TreeEditForm', 3],
    'access callback'   => 'ucms_tree_check_access_edit',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  $items['node/add/here'] = [
    'title'           => 'Add content at position',
    'page callback'   => 'sf_dic_page',
    'page arguments'  => ['MakinaCorpus\Ucms\Tree\Controller\TreeController::addContentHere'],
    'access callback' => ['ucms_tree_check_access_admin'],
    'type'            => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Menu access helper
 */
function ucms_tree_check_access_admin() {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Tree\MenuAccess $helper */
  $helper = \Drupal::service('ucms_tree.menu_access');
  $manager = ucms_site_manager();
  if ($manager->hasContext()) {
    return $helper->canAccessMenuAdmin($account, $manager->getContext());
  } else {
    return $helper->canAccessMenuAdmin($account);
  }
}

/**
 * Menu access helper
 */
function ucms_tree_check_access_create() {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Tree\MenuAccess $helper */
  $helper = \Drupal::service('ucms_tree.menu_access');
  $manager = ucms_site_manager();
  if ($manager->hasContext()) {
    return $helper->canCreateMenu($account, $manager->getContext());
  } else {
    return $helper->canCreateMenu($account);
  }
}

/**
 * Menu access helper
 */
function ucms_tree_check_access_edit(Menu $menu) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Tree\MenuAccess $helper */
  $helper = \Drupal::service('ucms_tree.menu_access');
  return $helper->canEditTree($menu, $account);
}

/**
 * Implements hook_library().
 */
function ucms_tree_library() {
  $path = drupal_get_path('module', 'ucms_tree');
  return [
    'nested-sortable' => [
      'title'        => 'Nested Sortable',
      'website'      => 'https://github.com/ilikenwf/nestedSortable',
      'version'      => '2.0-alpha',
      'js'           => [
        $path . '/js/jquery.nestedSortable.js' => [],
        $path . '/js/ucms_tree.js'             => [],
      ],
      'css'          => [
        $path . '/ucms_tree.css' => [
          'type'  => 'file',
          'media' => 'screen',
        ],
      ],
      'dependencies' => [
        ['system', 'ui.sortable'],
      ],
    ],
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ucms_tree_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($_GET['menu_name'])) {

    // Verify access to menu
    $matches = [];
    preg_match('@.*-(\d+)@', $_GET['menu_name'], $matches);
    $manager = ucms_site_manager();
    $site = $manager->getContext();
    $account = \Drupal::currentUser();
    if (!$site
      || $site->getId() !== $matches[1]
      || !$manager->getAccess()->userIsWebmaster($account, $site)) {
      drupal_access_denied();
      exit;
    }

    // Add GET parameters to form
    $form['menu'] = [
      '#tree' => TRUE,
    ];
    $form['menu']['menu_name'] = [
      '#type'  => 'value',
      '#value' => $_GET['menu_name'],
    ];
    $form['menu']['plid'] = [
      '#type'  => 'value',
      '#value' => !empty($_GET['parent']) ? $_GET['parent'] : 0,
    ];
    $form['menu']['position'] = [
      '#type'  => 'value',
      '#value' => $_GET['position'],
    ];
  }
}

/**
 * Implements hook_node_insert().
 */
function ucms_tree_node_insert($node) {
  // We handle only insert
  if (isset($node->menu)) {
    $link = &$node->menu;
    $link['link_title'] = $node->title;
    $link['link_path'] = "node/$node->nid";
    $link['expanded'] = 1;

    // Calculate the position depending on siblings
    $siblings = menu_build_tree($node->menu['menu_name'], [
      'plid' => $node->menu['plid'],
    ]);
    $index = 0;
    $previous_sibling_weight = -100;
    $weight_proposition = -100;
    foreach ($siblings as $sibling) {
      $sibling_weight = (int)$sibling['link']['weight'];
      if ($node->menu['position'] == $index) {
        // Take the half between prev sibling weight and the sibling's
        $weight_proposition = $sibling_weight - ($sibling_weight - $previous_sibling_weight) / 2;
      }
      $previous_sibling_weight = $sibling_weight;
      $index++;
    }
    $link['weight'] = $weight_proposition;

    if (!menu_link_save($link)) {
      drupal_set_message(t('There was an error saving the menu link.'), 'error');
    }
  }
}


/**
 * Implements hook_node_delete().
 */
function ucms_tree_node_delete($node) {
  // Delete all menu module links that point to this node.
  $mlids = db_select('menu_links', 'ml')
    ->fields('ml', ['mlid'])
    ->condition('link_path', 'node/' . $node->nid)
    ->condition('module', 'menu')
    ->execute()
    ->fetchCol()
  ;
  foreach ($mlids as $mlid) {
    menu_link_delete($mlid);
  }
}
