<?php
/**
 * UCMS - Dashboard and fioritures.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_page_attachments().
 */
function ucms_dashboard_page_attachments(array &$attachments) {
  // Attach seven theme fixes if enabled
  $themeManager = \Drupal::theme();
  if ('seven' === $themeManager->getActiveTheme()->getName()) {
    $attachments['#attached']['library'][] = 'ucms_dashboard/ucms_dashboard.seven_fixes';
  }
}

/**
 * Implements hook_entity_operation().
 */
function ucms_dashboard_entity_operation(EntityInterface $entity) {
  $ret = [];

  /** @var \MakinaCorpus\Ucms\Dashboard\Action\ActionRegistry $actionRegistry */
  $actionRegistry = \Drupal::service('ucms_dashboard.action_provider_registry');

  if ($actions = $actionRegistry->getActions($entity)) {
    /** @var \MakinaCorpus\Ucms\Dashboard\Action\Action $action */
    foreach ($actions as $action) {
      $ret[$action->getDrupalId()] = [
        'title' => $action->getTitle(),
        'url' => $action->getDrupalUrl(),
        'weight' => (0 - $action->getPriority()),
      ];
    }
  }

  return $ret;
}

/**
 * Implements hook_user_login().
 *
function ucms_dashboard_user_login(&$edit, $account) {
  // When a user logs in, he must be redirected to main dashboard.
  if (drupal_is_cli()) {
    return; // Make drush happy.
  }
  if (ucms_site_manager()->hasContext()) {
    return; // Let sites handle their own frontpage.
  }
  $GLOBALS['ucms_dashboard_login_redirect'] = true;
}
 */

/**
 * Implements hook_drupal_goto_alter().
 *
function ucms_dashboard_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  // This is the most proper way to provide a user login redirect.
  if (!empty($GLOBALS['ucms_dashboard_login_redirect'])) {
    if (isset($_GET['destination'])) {
      return; // Do not alter proper redirect.
    }
    $path = 'admin/dashboard';
  }
}
 */

/**
 * Implements hook_page_build().
 *
function ucms_dashboard_page_build(&$page) {
  if (user_is_logged_in() || path_is_admin(current_path())) {
    $page['page_top']['ucms_dashboard_top'] = [
      '#theme' => 'ucms_dashboard_top',
      '#links' => [
        '#theme' => 'links__main_menu',
        '#links' => $links,
      ],
    ];
  }
}
 */
