<?php
/**
 * UCMS - Dashboard and fioritures.
 */

/**
 * Implements hook_menu().
 */
function ucms_dashboard_menu() {

  $items = [];

  $items['admin/dashboard'] = [
    'title'             => "Dashboard",
    'page callback'     => 'ucms_dashboard_page',
    'access arguments'  => ['access administration pages'],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'ucms_dashboard.pages.inc',
  ];

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function ucms_dashboard_menu_alter(&$items) {

  // Remove all the unnecessary pages using the 'access administration pages'
  // or whatever else permission the users may have.
  foreach ([
    'admin/compact',
    'admin/config',
    'admin/config/content',
    'admin/config/development',
    'admin/config/media',
    'admin/config/regional',
    'admin/config/search',
    'admin/config/services',
    'admin/config/system',
    'admin/config/user-interface',
    'admin/config/workflow',
    'admin/index',
    'admin/reports/status/rebuild',
    'admin/structure',
  ] as $path) {
    $items[$path]['access arguments'] = ['non existing permission'];
  }

  // Single override where we change the 'admin' home page.
  $items['admin'] = [
    'title'             => "Administration",
    'page callback'     => 'ucms_dashboard_admin_redirect',
    'access arguments'  => ['access administration pages'],
    'type'              => MENU_CALLBACK,
  ];
}

/**
 * Menu callback.
 */
function ucms_dashboard_admin_redirect() {
  drupal_goto('admin/dashboard');
}

/**
 * Implements hook_theme().
 */
function ucms_dashboard_theme() {
  return [
    'ucms_dashbaord_page' => [
      'variables' => [],
      'template' => 'ucms_dashboard-page',
    ],
    'ucms_dashboard_page_list' => [
      'variables' => [
        'display' => null,
        'filters' => [],
        'items'   => [],
        'search'  => null,
        'pager'   => null,
      ],
      'template' => 'ucms_dashboard-page-list',
    ],
    'ucms_dashboard_top' => [
      'template' => 'ucms_dashboard-top',
    ],
  ];
}

/**
 * Implements hook_page_build().
 */
function ucms_dashboard_page_build(&$page) {
  if (!path_is_admin(current_path())) {
    return;
  }
  $page['page_top']['ucms_dashboard_top'] = [
    '#theme' => 'ucms_dashboard_top',
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_ucms_dashboard_page_list(&$variables) {

  /* @var $display \MakinaCorpus\Ucms\Dashboard\Page\DisplayInterface */
  $display = $variables['display'];

  $variables['displayView']   = $display->render($variables['items']);
  $variables['displayLinks']  = $display->renderLinks();

  /* @var $filter \MakinaCorpus\Ucms\Dashboard\Page\FilterDisplayInterface */
  foreach ($variables['filters'] as $index => $filter) {
    $variables['filters'][$index] = $filter->render();
  }
}

