<?php
/**
 * @file
 * UCMS - Unmeaningful legacy features that will be dropped.
 *
 * Please, never use this module.
 */

use Drupal\node\NodeInterface;
use MakinaCorpus\Drupal\Dashboard\Page\PageBuilder;
use MakinaCorpus\Ucms\Contrib\Page\DefaultNodeAdminPage;
use MakinaCorpus\Ucms\Harm\Form\NodeMakeGroup;
use MakinaCorpus\Ucms\Harm\Form\NodeUnmakeGroup;
use MakinaCorpus\Ucms\Site\Access;

/**
 * Implements hook_menu().
 */
function ucms_harm_menu() {

  // Prevent using service during install.
  if (defined('MAINTENANCE_MODE')) {
    return [];
  }

  $items = [];

  // Main administration pages.
  foreach (array_keys(ucms_contrib_type_handler_get()->getTabs()) as $key) {
    $items['admin/dashboard/' . $key . '/group'] = [
      'title'             => "Group",
      'page callback'     => 'ucms_harm_admin_content_page_group',
      'page arguments'    => [$key],
      'access arguments'  => [Access::PERM_CONTENT_VIEW_GROUP],
      'type'              => MENU_LOCAL_TASK,
      'weight'            => 100,
    ];
  }

  $items['node/%node/make-group'] = [
    'title'             => "Define as group content",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => [NodeMakeGroup::class, 1],
    'access callback'   => 'ucms_harm_menu_node_access_group',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['node/%node/unmake-group'] = [
    'title'             => "Remove from group contents",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => [NodeUnmakeGroup::class, 1],
    'access callback'   => 'ucms_harm_menu_node_access_group',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  return $items;
}

/**
 * Menu access helper.
 */
function ucms_harm_menu_node_access_group(NodeInterface $node) {
  sf_acl_is_granted(Access::ACL_PERM_CONTENT_PROMOTE_GROUP, $node);
}

/**
 * Group content admin.
 */
function ucms_harm_admin_content_page_group($tab = null) {
  /** @var \MakinaCorpus\Ucms\Contrib\Page\ElasticNodeDataSource $datasource */
  $datasource = \Drupal::service('ucms_contrib.datasource.elastic');
  $search = $datasource->getSearch();
  $search->getFilterQuery()->matchTerm('is_group', 1);
  require_once drupal_get_path('module', 'ucms_contrib') . '/ucms_contrib.pages.inc';
  return ucms_harm_admin_content_page($datasource, $tab);
}

/**
 * Legacy function to display an admin page.
 *
 * @deprecated
 */
function ucms_harm_admin_content_page($datasource, $tab) {
  /** @var \MakinaCorpus\Ucms\Contrib\Page\ElasticNodeDataSource $datasource */
  $datasource = \Drupal::service('ucms_contrib.datasource.elastic');
  /** @var \MakinaCorpus\Ucms\Site\SiteManager $siteManager */
  $siteManager = \Drupal::service('ucms_site.manager');
  /** @var \MakinaCorpus\Ucms\Contrib\TypeHandler $typeHandler */
  $typeHandler = \Drupal::service('ucms_contrib.type_handler');

  $type = new DefaultNodeAdminPage($datasource,
    $siteManager,
    $typeHandler,
    null,
    $tab = null,
    ['type' => $typeHandler->getTabTypes($tab)],
    false
  );

  $builder = new PageBuilder(\Drupal::service('twig'));
  $type->build($builder);
  $result = $builder->search($datasource, \Drupal::request());

  return $builder->createPageView($result)->render();
}
