<?php
/**
 * @file
 * UCMS - Unmeaningful legacy features that will be dropped.
 *
 * Please, never use this module.
 */

use Drupal\node\NodeInterface;
use MakinaCorpus\Ucms\Harm\Form\NodeMakeGroup;
use MakinaCorpus\Ucms\Harm\Form\NodeUnmakeGroup;
use MakinaCorpus\Ucms\Site\Access;

/**
 * Implements hook_menu().
 */
function ucms_harm_menu() {

  // Prevent using service during install.
  if (defined('MAINTENANCE_MODE')) {
    return [];
  }

  $items = [];

  $items['node/%node/make-group'] = [
    'title'             => "Define as group content",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => [NodeMakeGroup::class, 1],
    'access callback'   => 'ucms_harm_menu_node_access_group',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['node/%node/unmake-group'] = [
    'title'             => "Remove from group contents",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => [NodeUnmakeGroup::class, 1],
    'access callback'   => 'ucms_harm_menu_node_access_group',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  return $items;
}

/**
 * Menu access helper.
 */
function ucms_harm_menu_node_access_group(NodeInterface $node) {
  sf_acl_is_granted(Access::ACL_PERM_CONTENT_PROMOTE_GROUP, $node);
}
