<?php
/**
 * @file
 * UCMS - Label management.
 */


use MakinaCorpus\Ucms\Label\LabelAccess;


/**
 * Implements hook_menu().
 */
function ucms_label_menu() {
  $items = [];

  $items['admin/dashboard/label'] = [
    'title'             => "Labels",
    'page callback'     => 'ucms_label_dashboard_label_list',
    'access arguments'  => [LabelAccess::PERM_ACCESS_DASHBOARD],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'ucms_label.dashboard.inc',
  ];

  $items['admin/dashboard/label/add'] = [
    'title'             => "Add new label",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Label\Form\LabelEdit'],
    'access callback'   => 'ucms_label_access_manage',
    'access arguments'  => [LabelAccess::OP_ADD],
    'type'              => MENU_NORMAL_ITEM,
  ];

  $items['admin/dashboard/label/%taxonomy_term/edit'] = [
    'title callback'    => 'ucms_label_menu_item_title',
    'title arguments'   => [LabelAccess::OP_EDIT, 3],
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Label\Form\LabelEdit', 3],
    'access callback'   => 'ucms_label_access_manage',
    'access arguments'  => [LabelAccess::OP_EDIT, 3],
    'type'              => MENU_CALLBACK,
  ];

  $items['admin/dashboard/label/%taxonomy_term/delete'] = [
    'title callback'    => 'ucms_label_menu_item_title',
    'title arguments'   => [LabelAccess::OP_DELETE, 3],
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Label\Form\LabelDelete', 3],
    'access callback'   => 'ucms_label_access_manage',
    'access arguments'  => [LabelAccess::OP_DELETE, 3],
    'type'              => MENU_CALLBACK,
  ];

  return $items;
}


/**
 * Implements hook_permission().
 */
function ucms_label_permission() {
  return [
    LabelAccess::PERM_ACCESS_DASHBOARD => [
      'title' => t("View labels"),
    ],
    LabelAccess::PERM_EDIT_LOCKED => [
      'title' => t("Edit locked labels"),
    ],
    LabelAccess::PERM_EDIT_NON_LOCKED => [
      'title' => t("Edit non locked labels"),
    ],
  ];
}


/**
 * Checks the user's permissions for operations on labels.
 */
function ucms_label_access_manage($op, $label = null, $account = null) {
  if (!$account) {
    global $user;
    $account = $user;
  }

  $manager = \Drupal::service('ucms_label.manager');

  switch ($op) {
    case LabelAccess::OP_ADD:
      return $manager->canEditNonLockedLabels($account) || $manager->canEditLockedLabels($account);

    case LabelAccess::OP_DELETE:
      if ($manager->hasChildren($label)) {
        return false;
      }

    case LabelAccess::OP_EDIT:
      return $manager->canEditLabel($label, $account);
  }

  return false;
}


/**
 * Checks the user's permissions for operations on labels.
 */
function ucms_label_menu_item_title($op, $label) {
  switch ($op) {
    case LabelAccess::OP_EDIT:
      return t("Edit \"@name\" label", ['@name' => $label->name]);
    case LabelAccess::OP_DELETE:
      return t("Delete \"@name\" label", ['@name' => $label->name]);
  }
}
