calista:
  pages:

    ucms_tree.list_all:
      datasource: ucms_tree.admin.datasource
      input:
        pager_enable: false
      view:
        properties: {}
        show_filters: true
        show_pager: false
        templates:
          default: "@ucms_tree/Page/page-tree-admin.html.twig"
        view_type: twig_page
