<?php
/**
 * Brings the 'group' feature to µCMS.
 *
 * Group features allows to create arbitrary groups, which may contain both
 * sites and users. Once enabled, new set of user rights, such as site and
 * content visibility throught the admin will be altered to match the groups.
 */

use MakinaCorpus\Ucms\Group\Controller\DashboardController;
use MakinaCorpus\Ucms\Group\Group;
use MakinaCorpus\Ucms\Group\GroupAccess;

/**
 * Implements hook_permission().
 */
function ucms_group_permission() {
  return [
    GroupAccess::PERM_DASHBOARD_ACCESS => [
      'title' => t("Access to group dashboard"),
    ],
    GroupAccess::PERM_MANAGE_ALL => [
      'title' => t("Manage all groups"),
    ],
    GroupAccess::PERM_VIEW_ALL => [
      'title' => t("View all groups"),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function ucms_group_menu() {
  $items = [];

  // Dashboard callbacks
  $items['admin/dashboard/group'] = [
    'title'             => "Groups",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewMineAction'],
    'access arguments'  => [GroupAccess::PERM_DASHBOARD_ACCESS],
    'type'              => MENU_NORMAL_ITEM,
  ];
  $items['admin/dashboard/group/mine'] = [
    'title'             => "My groups",
    'type'              => MENU_DEFAULT_LOCAL_TASK,
    'weight'            => -100,
  ];
  $items['admin/dashboard/group/all'] = [
    'title'             => "All groups",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewAllAction'],
    'access arguments'  => [GroupAccess::PERM_VIEW_ALL],
    'type'              => MENU_LOCAL_TASK,
  ];
  $items['admin/dashboard/group/add'] = [
    'title'             => "Add group",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::addAction'],
    'access arguments'  => [GroupAccess::PERM_MANAGE_ALL],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Single group callbacks
  $items['admin/dashboard/group/%ucms_group_menu'] = [
    'title'             => "Group details",
    'title callback'    => 'ucms_group_menu_title',
    'title arguments'   => [3],
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/edit'] = [
    'title'             => "Edit",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::editAction', 3],
    'access callback'   => 'ucms_group_menu_access_edit',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Members administration
  $items['admin/dashboard/group/%ucms_group_menu/members'] = [
    'title'             => "Members",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::memberListAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/members/add'] = [
    'title'             => "Add member",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::memberAddAction', 3],
    'access callback'   => 'ucms_group_menu_access_manage_members',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Sites administration
  $items['admin/dashboard/group/%ucms_group_menu/sites'] = [
    'title'             => "Sites",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::siteListAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/sites/add'] = [
    'title'             => "Add site",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::siteAddAction', 3],
    'access callback'   => 'ucms_group_menu_access_manage_members',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  return $items;
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_load($id) {
  try {
    return \Drupal::service('ucms_group.manager')->getStorage()->findOne($id);
  } catch (\Exception $e) {}
  return false;
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_view(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Group\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->getAccess()->userCanView($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_manage(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Group\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->getAccess()->userCanManageAll($account);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_manage_members(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Group\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->getAccess()->userCanManageMembers($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_edit(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Group\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->getAccess()->userCanEdit($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_title(Group $group) {
  return $group->getTitle();
}

/**
 * Implements hook_form_node_form_alter().
 */
function ucms_group_form_node_form_alter(&$form, &$form_state) {
  $node = $form_state['node'];

  if ($node->group_id) {

    // Add the group options fieldset in node vertical tabs
    $form['group_information'] = [
      '#type'           => 'fieldset',
      '#title'          => t("Group options"),
      '#group'          => 'additional_settings',
    ];

    $form['group_information']['is_ghost'] = [
      '#type'           => 'checkbox',
      '#title'          => t("Content is hidden outside of this group"),
      '#default_value'  => $node->is_ghost,
      '#description'    => t("If you check this option, this content will be invisible outside of this group, except in sites it's being displayed into."),
    ];
  }
}

/**
 * Implements hook_query_TAG_alter().
 *
 * Implement site visibility access control for the admin UI, this is the only
 * query alteration for business purpose this module will ever do.
 */
function ucms_group_query_ucms_site_access_alter(QueryAlterableInterface $query) {

  if (!$query instanceof SelectQueryInterface) {
    return;
  }

  /* @var $account AccountInterface */
  if (!$account = $query->getMetaData('account')) {
    $account = \Drupal::currentUser();
  }

  $siteAlias  = null;
  $groupAlias = null;

  // If no base table is specified explicitly, search for one.
  foreach ($query->getTables() as $alias => $table_info) {
    if (!($table_info instanceof SelectQueryInterface)) {
      // If the node table is in the query, it wins immediately.
      if ('ucms_site' === $table_info['table']) {
        $siteAlias = $alias;
      }
      if ('ucms_group_site' === $table_info['table']) {
        $groupAlias = $alias;
      }
    }
  }

  if (!$siteAlias && !$groupAlias) {
    return;
  }

  /** @var \MakinaCorpus\Ucms\Group\GroupManager $groupManager */
  $groupManager = \Drupal::service('ucms_group.manager');
  $accessList   = $groupManager->getAccess()->getUserGroups($account);

  // Normal user rights coming in!
  if (!$accessList) {
    return;
  }

  $groupList = [];
  foreach ($accessList as $access) {
      $groupList[] = $access->getGroupId();
  }

  if (!$groupAlias) {
    $query->join(
      'ucms_group_site',
      'access_sg',
      "access_sg.site_id = " . $siteAlias . ".id AND access_sg.group_id IN (:access_sg_group)",
      [':access_sg_group' => $groupList]
    );
  } else {
    $query->condition($groupAlias . '.group_id', $groupList);
  }
}
