<?php
/**
 * @file
 * µCMS notifications module.
 *
 * This module has been separated from the rest in order to remain decoupled
 * from the APubSub notification system, and deactivable.
 */

use MakinaCorpus\APubSub\Notification\EventDispatcher\ResourceEvent;

  /*
   * Testing code
   *

  /* @var $n \MakinaCorpus\APubSub\Notification\NotificationService * /
  $n = \Drupal::service('apb.notification');
  $n->getBackend()->createChannel('site.admin');
  $n->getSubscriber(1)->subscribe('site.admin');
  $n->getSubscriber(6)->subscribe('site.admin');

  \Drupal::service('apb.notification')->subscribe('node', range(1, 50), 1);
  \Drupal::service('apb.notification')->subscribe('node', ['a', 'b', 'c', 'd'], 1);
  \Drupal::service('apb.notification')->subscribe('node', range(1, 50), 6);
  \Drupal::service('apb.notification')->subscribe('node', ['a', 'b', 'c', 'd'], 6);

  // Testing code.
  $nids = [1,2,3,4,5,6,7,8,9,10];
  $uids = [1,2,3,6,7,8];
  \Drupal::service('apb.notification')->notify('node', $nids, 'update', ['uid' => $uids]);

  $nids = [22, 23];
  $uids = [1,2];
  \Drupal::service('apb.notification')->notify('node', $nids, 'update', ['uid' => $uids]);

  \Drupal::service('apb.notification')->notify('node', [1], 'update', ['uid' => [2]]);
  \Drupal::service('apb.notification')->notify('node', [1], 'update', ['uid' => [6]]);
  \Drupal::service('apb.notification')->notify('node', ['a'], 'update', ['uid' => [2]]);
  \Drupal::service('apb.notification')->notify('node', ['a', 'b', 'c', 'd'], 'update', ['uid' => [6]]);

  die("done");

   */

/**
 * Implements hook_node_udpate().
 */
function ucms_notification_node_update($node) {
  global $user;
  /* @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
  $dispatcher = \Drupal::service('event_dispatcher');
  $dispatcher->dispatch('node:update', new ResourceEvent('node', $node->nid, $user->uid));
}
