<?php
/**
 * @file
 * UCMS Search feature.
 *
 * @todo
 *   - Use the bulk API whenever possible
 *   - Decoralate node index on cron and node index now
 *   - Investigate if index without delay is possible (node_insert via ui)
 *   - Fix node delete from index
 *   - Add flexible schema (configurable dependent on fields)
 *   - Allow multiple facet widgets
 *   - Add checkbox based facet
 *   - Add sort widgets
 *   - Add drush integration
 *   - Decoralate Lucene query builder and Lucene query string formatting
 *   - Add Elastic search array query formatting (must, must not, etc...)
 */

/**
 * Public index name.
 */
define('UCMS_SEARCH_INDEX_PUBLIC', variable_get('ucms_search_elastic_index_front', 'node_public'));

/**
 * Backoffice index name.
 */
define('UCMS_SEARCH_INDEX_BACK', variable_get('ucms_search_elastic_index_back', 'node_backoffice'));

/**
 * Default search per page limit.
 */
const UCMS_SEARCH_LIMIT = 100;

/**
 * Default number of items index each cron run.
 */
const UCMS_SEARCH_CRON_INDEX_LIMIT = 250;

/**
 * Index operations.
 */
require_once __DIR__ . '/ucms_search.index.inc';

/**
 * Implements hook_boot().
 */
function ucms_search_boot() {
  if (!module_exists('composer_manager')) {
    if (!@include_once __DIR__ . '/../vendor/autoload.php') {
      watchdog(__FUNCTION__, "Missing composer autoload.php file", [], WATCHDOG_ERROR);
    }
  }
}

/**
 * Implements hook_menu().
 */
function ucms_search_menu() {
  $items = [];

  $items['admin/config/search/indices'] = [
    'title'             => "Search indices",
    'page callback'     => 'drupal_get_form',
    'page arguments'    => ['ucms_search_admin_index_form'],
    'access arguments'  => ['administer nodes'],
    'description'       => "Manage search indices.",
    'file'              => 'ucms_search.admin.inc',
    'type'              => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function ucms_search_theme() {
  return [
    'ucms_search_facet' => [
      'variables' => ['facet' => null],
    ],
  ];
}

/**
 * Get elastic search client.
 *
 * @return \Elasticsearch\Client
 */
function ucms_search_client_get() {
  $instance = &drupal_static(__FUNCTION__);
  if (!$instance) {
    $hosts = variable_get('ucms_search_elastic_hosts', 'localhost:9200');
    if (!is_array($hosts)) {
      $hosts = [$hosts];
    }
    $instance = \Elasticsearch\ClientBuilder::create()->setHosts($hosts)->build();
  }
  return $instance;
}

/**
 * Create new search
 *
 * @param string $index
 *
 * @return \Ucms\Search\QueryAlteredSearch
 */
function ucms_search_create($index) {
  return (new \Ucms\Search\QueryAlteredSearch(ucms_search_client_get()))->setIndex($index);
}

/**
 * Get node indexes.
 *
 * @return string[]
 */
function ucms_search_index_list() {
  return [
    UCMS_SEARCH_INDEX_PUBLIC  => t("Front-office search index"),
    UCMS_SEARCH_INDEX_BACK    => t("Back-office content administration page index"),
  ];
}

/**
 * Implements hook_ucms_search_index_reindex().
 */
function ucms_search_ucms_search_index_reindex($index, SelectQueryInterface $query) {
  switch ($index) {

    case UCMS_SEARCH_INDEX_PUBLIC:
      $query->condition('n.status', 1);
      break;
  }
}

/**
 * Implements hook_ucms_search_index_node().
 */
function ucms_search_ucms_search_index_node($index, $node) {
  switch ($index) {

    case UCMS_SEARCH_INDEX_PUBLIC:
      if ($node->status) {
        return true;
      }
      break;

    case UCMS_SEARCH_INDEX_BACK:
      return true;
  }
}

/**
 * Implements hook_ucms_search_index_reindex().
 */
function ucms_search_node_index_now($node) {
  foreach (array_keys(ucms_search_index_list()) as $index) {
    if (!$node->is_new && $node->created != $node->changed) {
      ucms_search_index_node_update($index, $node);
    } else {
      ucms_search_index_node_add($index, $node);
    }
  }
  sleep(2);
}

/**
 * Enqueue node to reindex.
 *
 * @param int|int[] $nidList
 */
function ucms_search_node_index_queue($nidList) {
  if (!is_array($nidList)) {
    $nidList = [$nidList];
  }
  $queue = &drupal_static('ucms_search_node_queue', []);
  $queue = array_merge($queue, $nidList);
  $queue = array_unique($queue);
}

/**
 * Implements hook_exit().
 */
function ucms_search_exit() {
  $queue = &drupal_static('ucms_search_node_queue');
  if ($queue) {
    foreach (array_keys(ucms_search_index_list()) as $index) {
      ucms_search_index_reindex($index, $queue);
    }
    drupal_static_reset('ucms_search_node_queue');
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ucms_search_form_node_form_alter(&$form, &$form_state) {
  // If a node is modified from the node form, we must index it right now
  // so that when the user returns on the node admin pages, he'll see nodes
  // right away. This must be an opt-in behavior, false by default, in order
  // to avoid any batch updating nodes from triggering this once per node.
  $form['ucms_index_now'] = ['#type' => 'value', '#value' => true];
}

/**
 * Implements hook_node_insert().
 */
function ucms_search_node_insert($node) {
  if (isset($node->ucms_index_now) && $node->ucms_index_now) {
    ucms_search_node_index_now($node);
    sleep(2);  // FIXME
  } else {
    ucms_search_node_index_queue([$node->nid]);
  }
}

/**
 * Implements hook_node_update().
 */
function ucms_search_node_update($node) {
  if (isset($node->ucms_index_now) && $node->ucms_index_now) {
    ucms_search_node_index_now($node);
    sleep(2); // FIXME
  } else {
    ucms_search_node_index_queue([$node->nid]);
  }
}

/**
 * Implements hook_node_delete().
 */
function ucms_search_node_delete($node) {
  // @todo Later queue and bulk
  foreach (array_keys(ucms_search_index_list()) as $index) {
    ucms_search_index_node_delete($index, $node);
  }
}

/**
 * Implements hook_cron().
 */
function ucms_search_cron() {
  ucms_search_cron_index_dequeue();
}

/**
 * Renders a search facet.
 */
function theme_ucms_search_facet($variables) {
  $facet = $variables['facet'];

  // @todo Improve this
  if ($facet instanceof \Ucms\Search\TermFacet) {

    $links    = [];
    $field    = $facet->getField();
    $values   = $facet->getSelectedValues();
    $choices  = $facet->getFormattedChoices();

    if (empty($choices)) {
      // There is no choice for this field.
      $links['_empty'] = t("No values");

    } else if (1 === count($choices)) {
      // There is only one choice, and it might or might not be selected.
      foreach ($choices as $value => $string) {
        if (in_array($value, $values)) {
          $links[$value] = l('- ' . $string, current_path(), [
            'query' => drupal_get_query_parameters(null, [$field, 'q', 'page']),
            'html'  => true,
          ]);
        } else {
          $links[$value] = $string;
        }
      }

    } else {
      // There is more than once choice, some might be selected.
      foreach ($choices as $value => $string) {
        if (in_array($value, $values)) {
          $links[$value] = l('- ' . $string, current_path(), [
            'query' => drupal_get_query_parameters(null, [$field, 'q', 'page']),
            'html'  => true,
          ]);
        } else {
          $links[$value] = l($string, current_path(), [
            'query' => [$field => $value] + drupal_get_query_parameters(null, ['q', 'page']),
            'html'  => true,
          ]);
        }
      }
    }

    return theme('item_list__ucms_search_facet_terms', ['title' => $facet->getTitle(), 'items' => $links]);
  }
}
