<?php
/**
 * Brings the 'group' feature to µCMS.
 *
 * Group features allows to create arbitrary groups, which may contain both
 * sites and users. Once enabled, new set of user rights, such as site and
 * content visibility throught the admin will be altered to match the groups.
 */

use MakinaCorpus\Ucms\Site\Group;
use MakinaCorpus\Ucms\Group\Controller\AutocompleteController;
use MakinaCorpus\Ucms\Group\Controller\DashboardController;
use MakinaCorpus\Ucms\Site\Access;

/**
 * Implements hook_menu().
 */
function ucms_group_menu() {
  $items = [];

  // Dashboard callbacks
  $items['admin/dashboard/group'] = [
    'title'             => "Groups",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewMineAction'],
    'access arguments'  => [Access::PERM_GROUP_DASHBOARD_ACCESS],
    'type'              => MENU_NORMAL_ITEM,
  ];
  $items['admin/dashboard/group/mine'] = [
    'title'             => "My groups",
    'type'              => MENU_DEFAULT_LOCAL_TASK,
    'weight'            => -100,
  ];
  $items['admin/dashboard/group/all'] = [
    'title'             => "All groups",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewAllAction'],
    'access arguments'  => ['access administration pages'],
    'type'              => MENU_LOCAL_TASK,
  ];
  $items['admin/dashboard/group/add'] = [
    'title'             => "Add group",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::addAction'],
    'access arguments'  => [Access::PERM_GROUP_MANAGE_ALL],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Single group callbacks
  $items['admin/dashboard/group/%ucms_group_menu'] = [
    'title'             => "Group details",
    'title callback'    => 'ucms_group_menu_title',
    'title arguments'   => [3],
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::viewAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/edit'] = [
    'title'             => "Edit",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::editAction', 3],
    'access callback'   => 'ucms_group_menu_access_edit',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Members administration
  $items['admin/dashboard/group/%ucms_group_menu/members'] = [
    'title'             => "Members",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::memberListAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/members/add'] = [
    'title'             => "Add member",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::memberAddAction', 3],
    'access callback'   => 'ucms_group_menu_access_manage_members',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Sites administration
  $items['admin/dashboard/group/%ucms_group_menu/sites'] = [
    'title'             => "Sites",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::siteListAction', 3],
    'access callback'   => 'ucms_group_menu_access_view',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/sites/add'] = [
    'title'             => "Add site",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::siteAddAction', 3],
    'access callback'   => 'ucms_group_menu_access_manage_members',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/group/%ucms_group_menu/sites-add-ac'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [AutocompleteController::class . '::siteAddAutocompleteAction', 3],
    'type'              => MENU_CALLBACK,
  ];

  // Site actions
  $items['admin/dashboard/site/%ucms_site/group-attach'] = [
    'title'             => "Attach to group",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [DashboardController::class . '::siteAttachAction', 3],
    'access callback'   => true,
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/site/%ucms_site/group-attach/ac'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [AutocompleteController::class . '::siteAttachAutocompleteAction', 3],
    'type'              => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_load($id) {
  try {
    return \Drupal::service('ucms_group.manager')->findOne($id);
  } catch (\Exception $e) {}
  return false;
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_view(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Site\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->userCanView($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_manage(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Site\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->userCanManageAll($account);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_manage_members(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Site\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->userCanManageMembers($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_access_edit(Group $group) {
  $account = \Drupal::currentUser();
  /** @var \MakinaCorpus\Ucms\Site\GroupManager $manager */
  $manager = \Drupal::service('ucms_group.manager');
  return $manager->userCanEdit($account, $group);
}

/**
 * Menu helper, do not use.
 *
 * @deprecated
 */
function ucms_group_menu_title(Group $group) {
  return $group->getTitle();
}

/**
 * Implements hook_form_node_form_alter().
 */
function ucms_group_form_node_form_alter(&$form, &$form_state) {
  $node = $form_state['node'];

  if ($node->group_id) {

    // Add the group options fieldset in node vertical tabs
    $form['group_information'] = [
      '#type'           => 'fieldset',
      '#title'          => t("Group options"),
      '#group'          => 'additional_settings',
    ];

    $form['group_information']['is_ghost'] = [
      '#type'           => 'checkbox',
      '#title'          => t("Content is hidden outside of this group"),
      '#default_value'  => $node->is_ghost,
      '#description'    => t("If you check this option, this content will be invisible outside of this group, except in sites it's being displayed into."),
    ];
  }
}
