<?php
/**
 * @file
 * Ho, ho, µSEO, Santiano.
 *   - Tribute to Hugues Aufray.
 *
 * @todo
 *   - Widget form
 *       -> also needs a standalone form
 *   - menu tree building
 *       -> in a service
 *   - url_alias table handling (is_canonical)
 *       -> in a service
 *   - hook_page_build() to add canonical and meta information
 *     (also could be on node view when mode full, formatter?)
 *       -> in a service
 *   - global configuration (administer path, canonicals)
 */

use Drupal\node\NodeInterface;

use MakinaCorpus\Ucms\Seo\SeoService;
use MakinaCorpus\Ucms\Site\Site;

/**
 * Implements hook_menu().
 */
function ucms_seo_menu() {
  $items = [];

  $items['sitemap'] = [
    'title'             => "Sitemap",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Controller\SitemapController::display', 'html'],
    'access callback'   => TRUE,
    'type'              => MENU_CALLBACK,
  ];
  $items['sitemap.xml'] = array(
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Controller\SitemapController::display', 'xml'],
  ) + $items['sitemap'];

  $items['node/%node/seo-edit'] = [
    'title'             => "Edit SEO parameters",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Form\SeoNodeForm', 1],
    'access callback'   => 'ucms_seo_menu_access_node_edit',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['node/%node/seo-aliases'] = [
    'title'             => "Node path aliases",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Controller\SeoController::nodeAliasList', 1],
    'access callback'   => 'ucms_seo_menu_access_node_edit',
    'access arguments'  => [1],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  $items['admin/dashboard/site/%ucms_site/seo-aliases'] = [
    'title'             => "Site path aliases",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Controller\SeoController::siteAliasList', 3],
    'access callback'   => 'ucms_seo_menu_access_site_edit',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['admin/dashboard/site/%ucms_site/seo-edit'] = [
    'title'             => "Edit SEO parameters",
    'page callback'     => 'sf_dic_page_form',
    'page arguments'    => ['MakinaCorpus\Ucms\Seo\Form\SeoSiteForm', 3],
    'access callback'   => 'ucms_seo_menu_access_site_edit',
    'access arguments'  => [3],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  $items["node/%node/store-locator"] = [
    'page callback' => 'sf_dic_page',
    'page arguments' => ['MakinaCorpus\Ucms\Seo\Controller\StoreLocatorController::renderPage', 1, 3, 4, 5],
    'access callback' => 'ucms_seo_store_locator_access',
    'access arguments' => [1],
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function ucms_seo_admin_paths() {
  return [
    'node/*/seo-edit' => true,
    'node/*/seo-aliases' => true,
  ];
}

/**
 * Menu access helper.
 */
function ucms_seo_store_locator_access($node) {
  return in_array($node->type, variable_get('ucms_seo_store_locator_content_types', []), TRUE);
}

/**
 * Menu access helper.
 */
function ucms_seo_menu_access_site_edit(Site $site) {
  return ucms_seo_service()->userCanEditSiteSeo(\Drupal::currentUser(), $site);
}

/**
 * Menu access helper.
 */
function ucms_seo_menu_access_node_edit($node) {
  if ($node instanceof NodeInterface) {
    return ucms_seo_service()->userCanEditNodeSeo(\Drupal::currentUser(), $node);
  }
  return false;
}

/**
 * Implements hook_permission().
 */
function ucms_seo_permission() {
  return [
    SeoService::PERM_SEO_CONTENT_ALL => [
      'title' => t("Access platform wide SEO data"),
    ],
    SeoService::PERM_SEO_CONTENT_OWN => [
      'title' => t("Manage SEO data for own content"),
    ],
    SeoService::PERM_SEO_GLOBAL => [
      'title' => t("Manage SEO data for all content"),
    ],
  ];
}

/**
 * Implements hook_page_build().
 */
function ucms_seo_page_build(&$page) {
  $site = null;

  // This be better to be listener onResponse but hey, what Drupal can and
  // cannot do is way beyond the human comprehension level...
  $manager = ucms_site_manager();
  if ($manager->hasContext()) {
    $site = $manager->getContext();
    if ($site->hasAttribute('seo.google.site_verification')) {
      drupal_add_html_head([
        '#tag' => 'meta',
        '#attributes' => [
          'name' => 'google-site-verification',
          'content' => $site->getAttribute('seo.google.site_verification'),
        ],
      ], 'seo.google.site_verification');
    }
  }

  if ($site && !ucms_site_is_master() && !path_is_admin(current_path())) {
    if ($node = menu_get_object()) {

      foreach (ucms_seo_service()->getNodeMeta($node) as $name => $content) {
        drupal_add_html_head(['#tag' => 'meta', '#attributes' => ['name' => $name, 'content' => check_plain($content)]], 'meta-' . $name);
      }

      $canonical = null;

      if (drupal_is_front_page()) {
        // Do not set a canonical for home pages, just the site URL.
        $canonical = url('http://' . $site->http_host . '/');
      } else if ('node' === arg(0) && !arg(3)) {
        $canonical = ucms_seo_service()->getNodeCanonical($node) . '/';
        if (!$canonical) {
          $canonical = url('node/' . $node->nid, ['absolute' => true]) . '/';
        }
      }

      if ($canonical) {
        drupal_add_html_head(['#tag' => 'link', '#attributes' => ['rel' => 'canonical', 'href' => $canonical]], 'canonical');
      }
    }
    // Always add robots directives.
    drupal_add_html_head(['#tag' => 'meta', '#attributes' => ['name' => 'robots', 'content' => 'index,follow,all']], 'robots');
  }
}

/**
 * Implements hook_html_head_alter().
 */
function ucms_seo_html_head_alter(&$elements) {
  unset($elements['system_meta_generator']);
}

/**
 * @return \MakinaCorpus\Ucms\Seo\SeoService
 */
function ucms_seo_service() {
  return \Drupal::service('ucms_seo.seo_service');
}

/**
 * Element validate for segment.
 */
function ucms_seo_element_validate_segment($element, &$form_state) {
  $value = trim($element['#value']);
  if (empty($value)) {
    return;
  }
  if (false !== strpos($value, '/')) {
    form_error($element, t("SEO node alias cannot contain the / character"));
  }
  if (!preg_match('/^[a-z0-9_-]+$/', $value)) {
    form_error($element, t("SEO node alias can only contain non capital letters, numbers, _ and - characters"));
  }
  form_set_value($element, $value, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ucms_seo_form_node_form_alter(&$form, &$form_state) {

  $account = \Drupal::currentUser();
  $service = ucms_seo_service();

  $form['ucms_seo'] = [
    '#type'         => 'fieldset',
    '#title'        => t('SEO'),
    '#access'       => $account->hasPermission(SeoService::PERM_SEO_CONTENT_ALL) || $account->hasPermission(SeoService::PERM_SEO_CONTENT_OWN),
    '#collapsible'  => true,
    '#collapsed'    => false,
    '#group'        => 'additional_settings',
    '#weight'       => 100,
  ];

  $form['ucms_seo']['ucms_seo_segment'] = [
    '#type'           => 'textfield',
    '#maxlength'      => variable_get('ucms_seo.segment_max_length', 255),
    '#title'          => t("Node alias"),
    '#description'    => t("This alias must not contain the / character"),
    '#default_value'  => $service->getNodeSegment($form['#node']),
    '#attributes'     => ['placeholder' => 'welcome-to-my-site'],
    '#element_validate' => ['ucms_seo_element_validate_segment'],
    '#field_prefix'     => 'some/path/', // @todo
    '#weight'         => 100,
  ];
}

/**
 * Implements hook_theme().
 */
function ucms_seo_theme() {
  return [
    'ucms_seo_sitemap' => [
      'variables' => ['menus' => array()],
      'template'  => 'views/ucms-seo-sitemap',
    ],
    'ucms_seo_store_locator_map' => [
      'variables' => [
        'items' => [],
        'nodes' => [],
        'type' => NULL,
        'sub_area' => NULL,
        'locality' => NULL,
      ],
      'template' => 'views/ucms-seo-store-locator-map',
    ],
  ];
}
