# Default node admin pages
calista:
  pages:

    # Content administration page
    ucms_contrib.content_admin.content:
      datasource: ucms_contrib.datasource.node
      input:
        limit_default: 24
        pager_enable: true
        pager_param: page
        search_enable: true
        search_param: s
        sort_default_field: n.changed
      view:
        enabled_filters: ['type', 'status']
        properties: {}
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          table: '@calista/page/drupal/page-node-table.html.twig'
          grid: '@calista/page/drupal/page-node-grid.html.twig'
        view_type: twig_page

    # Media administration page
    ucms_contrib.content_admin.media:
      datasource: ucms_contrib.datasource.node
      input:
        limit_default: 24
        pager_enable: true
        pager_param: page
        search_enable: true
        search_param: s
        sort_default_field: n.changed
      view:
        default_display: grid
        enabled_filters: ['type', 'status']
        properties: {}
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          table: '@calista/page/drupal/page-node-table.html.twig'
          grid: '@calista/page/drupal/page-node-grid.html.twig'
        view_type: twig_page
