<?php
/**
 * @file
 * UCMS - Layout management module.
 *
 * For the sake of consistency, layouts cannot be nodes, otherwise layouts
 * could be embeded into layouts, which would make a serious and non human
 * comprehensible layout-ception. Problem with this model is that we need
 * to implement by ourselves the access API for layouts, but this is the
 * only custom access API that will be implemented at all.
 *
 * @todo
 *   - better AJAX/REST requests handling
 *   - more detailed data structure (options, status)
 *   - alteration for access checks
 *   - preview mode (display unauthorized or unpublished content)
 *   - non AJAX edit forms for accessibility
 *   - regions filtering (per-theme global configuration) and checks
 *   - unit testing (sorry should have done that earlier).
 */

/**
 * Hopefully, you did run composer install.
 */
require_once __DIR__ . '/vendor/autoload.php';

/**
 * Because we do need this.
 */
require_once __DIR__ . '/ucms_layout.crud.inc';

/**
 * FIXME: FOR TESTING, REMOVE ME THEN.
 */
function ucms_layout_init() {
  return;
  $layout = ucms_layout_load(1);
  foreach (array('content', 'sidebar_first', 'sidebar_second') as $name) {
    for ($i = 0; $i < rand(3, 10); ++$i) {
      $item = new \Ucms\Layout\Item(rand(100, 5000));
      switch (rand(0, 2)) {
        case 0:
          $layout->getRegion($name)->append($item);
          break;
        case 1:
          $layout->getRegion($name)->prepend($item);
          break;
        case 2:
          $layout->getRegion($name)->addAt($item, rand(0, 10));
          break;
      }
    }
  }
  ucms_layout_save($layout);
}

/**
 * Implements hook_menu().
 */
function ucms_layout_menu() {
  $items = [];

  // This is what the site is made for.
  $items['layout/%ucms_layout'] = [
    'title callback'    => 'ucms_layout_title',
    'title arguments'   => [1],
    'page callback'     => 'ucms_layout_blank',
    'page arguments'    => [1],
    'access callback'   => 'ucms_layout_access',
    'access arguments'  => ['view', 1],
    'type'              => MENU_CALLBACK,
  ];

  // Update and delete operations.
  $items['layout/%ucms_layout/edit'] = [
    'title'             => "Edit page",
    'page callback'     => 'drupal_get_form',
    'page arguments'    => ['ucms_layout_admin_layout_edit_form', 1],
    'access callback'   => 'ucms_layout_access',
    'access arguments'  => ['update', 1],
    'file'              => 'ucms_layout.admin.inc',
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];
  $items['layout/%ucms_layout/delete'] = [
    'title callback'    => 'ucms_layout_title',
    'title arguments'   => [1],
    'page callback'     => 'drupal_get_form',
    'page arguments'    => ['ucms_layout_admin_layout_delete_form', 1],
    'access callback'   => 'ucms_layout_access',
    'access arguments'  => ['delete', 1],
    'file'              => 'ucms_layout.admin.inc',
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  ];

  // Administration section.
  $items['admin/layout'] = [
    'title'             => "Pages",
    'page callback'     => 'ucms_layout_admin_index',
    'access arguments'  => ['access content overview'],
    'file'              => 'ucms_layout.admin.inc',
    'type'              => MENU_NORMAL_ITEM,
  ];
  $items['admin/layout/add'] = [
    'title'             => 'Add page',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => ['ucms_layout_admin_layout_add_form', 1],
    'access arguments'  => ['create layout'],
    'file'              => 'ucms_layout.admin.inc',
    'type'              => MENU_LOCAL_ACTION,
  ];

  // AJAX endpoints.
  $items['admin/ucms/layout/%ucms_layout/add'] = [
    'page callback'     => 'ucms_layout_ajax_region_item_add',
    'page arguments'    => [3],
    'access callback'   => 'ucms_layout_access',
    'access arguments'  => ['update', 3],
    'file'              => 'ucms_layout.ajax.inc',
    'type'              => MENU_CALLBACK,
  ];
  $items['admin/ucms/layout/%ucms_layout/remove'] = [
    'page callback'     => 'ucms_layout_ajax_region_item_remove',
    'page arguments'    => [3],
    'access callback'   => 'ucms_layout_access',
    'access arguments'  => ['update', 3],
    'file'              => 'ucms_layout.ajax.inc',
    'type'              => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function ucms_layout_admin_paths() {
  return [
    'layout/*/*' => true,
  ];
}

/**
 * Implements hook_permission().
 */
function ucms_layout_permission() {
  return [
    'create layout' => [
      'title' => t("Create a layout"),
    ],
    'update own layout' => [
      'title' => t("Update own layout"),
    ],
    'delete own layout' => [
      'title' => t("Delete own layout"),
    ],
    'update any layout' => [
      'title' => t("Update any layout"),
    ],
    'delete any layout' => [
      'title' => t("Delete any layout"),
    ],
  ];
}

/**
 * Layout access.
 *
 * @param string $op
 *   May be 'view', 'update' or 'delete'.
 * @param int|\Ucms\Layout\Layout $id
 *   Layout object or identifier.
 * @param stdClass $acount
 *   The account to check.
 *
 * @return boolean
 */
function ucms_layout_access($op, $layout, $account = null) {

  if (!$account) {
    $account = $GLOBALS['user'];
  }

  if (!$layout instanceof \Ucms\Layout\Layout) {
    $layout = ucms_layout_load($layout);
    if (!$layout) { // Is not a layout.
      return false;
    }
  }

  switch ($op) {

    case 'view':
      return user_access('access content', $account);

    case 'update':
      if (user_access('update any layout', $account)) {
        return true;
      }
      if (user_access('update own layout') && $account->uid == $layout->getId()) {
        return true;
      }
      return false;;

    case 'delete':
      if (user_access('delete any layout', $account)) {
        return true;
      }
      if (user_access('delete own layout') && $account->uid == $layout->getId()) {
        return true;
      }
      return false;;

    default:
      return false;
  }
}

/**
 * Get current contextual layout.
 *
 * @return \Ucms\Layout\Layout
 */
function ucms_layout_context_get($set = false) {
  $instance = &drupal_static(__FUNCTION__);
  if (false !== $set) {
    if (null === $set) {
      $instance = null;
    }
    if ($set instanceof \Ucms\Layout\Layout) {
      $instance = $set;
    }
  }
  return $instance;
}

/**
 * Menu title callback.
 */
function ucms_layout_title($layout) {
  if ($layout instanceof \Ucms\Layout\Layout) {
    return $layout->getTitle();
  }
  return t("Layout");
}

/**
 * Implements hook_theme().
 */
function ucms_layout_theme() {
  return [
    'ucms_layout_item' => [
      'variables' => ['nid' => null, 'node' => null, 'view_mode' => 'teaser'],
      'template'  => 'ucms-layout-item',
    ],
    'ucms_layout_region' => [
      'variables' => ['items' => [], 'name' => 'content'],
      'template'  => 'ucms-layout-region',
    ],
  ];
}

/**
 * Implements hook_block_list_alter().
 */
function ucms_layout_block_list_alter(&$blocks) {
  global $theme_key;

  foreach (system_region_list($theme_key) as $region => $title) {
    $next_key = max(array_keys($blocks)) + 1;
    $blocks[$next_key] = (object) [
      'bid' => $next_key,
      'cache' => 0,
      'custom' => 0,
      'delta' => $theme_key . ':' . $region,
      'module' => 'ucms_layout',
      'pages' => '',
      'region' => $region,
      'status' => 1,
      'title' => '',
      'visibility' => 0,
      'weight' => 0,
    ];
  }
}

/**
 * Implements hook_block_info().
 */
function ucms_layout_block_view($delta = '') {
  global $theme;

  if (!strpos($delta, ':')) {
    return; // Invalid delta.
  }

  $layout = ucms_layout_context_get();
  if (!$layout instanceof \Ucms\Layout\Layout) {
    return; // No layout on page.
  }

  list($btheme, $region) = explode(':', $delta, 2);
  if (!$btheme) {
    return; // No theme set.
  }
  if (!$region) {
    return; // No region set.
  }
  if ($btheme !== $theme) {
    return; // Wrong theme.
  }

  $items  = [];
  $region = $layout->getRegion($region);

  // Preload all nodes for performance.
  $nodeIdList = $region->getAllNodeIds();

  if ($nodeIdList) {
    $map = node_load_multiple($nodeIdList);

    $map = array_filter($map, function ($node) {
      return node_access('view', $node);
    });

    if (empty($map) && empty($_GET['edit'])) {
      return;
    }

    /* @var $item \Ucms\Layout\Item */
    foreach ($region as $item) {
      $nid = $item->getNodeId();
      if (isset($map[$nid])) {
        $items[] = [
          '#theme'      => 'ucms_layout_item',
          '#nid'        => $item->getNodeId(),
          '#node'       => $map[$nid],
          '#view_mode'  => $item->getViewMode(),
        ];
      }
    }
  } else if (empty($_GET['edit'])) {
    return;
  }

  if (empty($items)) {
    // Trick block.module so that it's not "empty"
    $items = ['#markup' => ''];
  }

  return ['content' => $items];
}

/**
 * Implements hook_preprocess_block().
 */
function ucms_layout_preprocess_block(&$vars) {
  // Add attributes and classes to block
  $block = $vars['block'];
  if ($block->module == 'ucms_layout') {
    $vars['attributes_array']['data-region'] = $block->region;
    $vars['classes_array'][] = 'ucms-layout-empty-block';
  }
}

/**
 * Implements hook_preprocess_block().
 */
function ucms_layout_preprocess_region(&$vars) {
  // Lookup for all blocks, if these are only ucms empty block, add class
  $empty = TRUE;
  foreach (element_children($vars['elements']) as $delta) {
    $block = $vars['elements'][$delta];
    if (!isset($block['#block']) || $block['#block']->module != 'ucms_layout' || empty($block['#type'])) {
      $empty = FALSE;
    }
  }
  if ($empty) {
    $vars['classes_array'][] = 'ucms-layout-empty-region';
  }
}


/**
 * Blank page.
 */
function ucms_layout_blank($layout) {
  if ($layout instanceof \Ucms\Layout\Layout) {
    ucms_layout_context_get($layout);
  }
  return [];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_ucms_layout_item(&$variables) {
  if (isset($variables['node'])) {
    $variables['content'] = node_view($variables['node'], $variables['view_mode']);
  } else {
    $variables['content'] = [];
  }
}
