calista:
  pages:

    ucms_group.list:
      datasource: ucms_group.admin.group_datasource
      input:
        limit_default: 24
        pager_enable: true
        search_enable: true
        sort_default_field: g.ts_changed
        sort_default_order: desc
      view:
        properties: {}
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          default: "@ucms_group/views/Page/groupAdmin.html.twig"
        view_type: twig_page

    ucms_group.list_members:
      datasource: ucms_group.admin.group_member_datasource
      input:
        limit_default: 24
        pager_enable: true
        search_enable: true
        sort_default_field: u.name
        sort_default_order: asc
      view:
        properties: {}
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          default: "@ucms_group/views/Page/groupMemberAdmin.html.twig"
        view_type: twig_page

    ucms_group.list_by_site:
      datasource: ucms_group.admin.group_site_datasource
      input:
        base_query: []
          # group: null # dynamically inject this (group from request)
        limit_default: 24
        pager_enable: true
        search_enable: true
        sort_default_field: s.title
        sort_default_order: asc
      view:
        properties: {}
        show_filters: true
        show_search: true
        show_sort: true
        templates:
          default: "@ucms_group/views/Page/groupSiteAdmin.html.twig"
        view_type: twig_page
