<?php
/**
 * UCMS  - Cart module.
 */

use MakinaCorpus\Ucms\Cart\Controller\CartController;

/**
 * Implements hook_menu().
 */
function ucms_cart_menu() {
  $items = [];

  $items['admin/cart/%node/add'] = [
    'title'             => "Content",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [CartController::class . '::add', 2],
    'access arguments'  => ['use favorites'],
  ];
  $items['admin/cart/%node/remove'] = [
    'title'             => "Content",
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [CartController::class . '::remove', 2],
    'access arguments'  => ['use favorites'],
  ];

  return $items;
}
