<?php
/**
 * @file
 * UCMS - Pseudo SSO accross sites.
 *
 * 1) User already connected on site SSO:
 *
 * Browser             Site X     Site SSO  cache(shared)
 *  |  GET /foo (ano.)    |           |
 *  |-------------------->|           |
 *  |   foo + sso js      |           |   token+domain:
 *  |<--------------------|           |  [session id +
 *  | Ajax /sso/check (+credentials)  |   IP + domain]
 *  |-------------------------------->|------>|
 *  |     json (one time token)       |       |
 *  |<--------------------------------|       |
 *  |GET /sso/login/token |                   |
 *  |-------------------->|  token + domain   |
 *  |                     |------------------>|
 *  |                     |    session_id     |
 *  |                     |<------------------|
 *  |  302 + session_id   |  here we also check the user IP
 *  |<--------------------|  is the same and sends the session_id
 *  |  get /foo (session) |  as a valid X domain cookie.
 *  |-------------------->|
 *  | foo (authenticated) |
 *  |<--------------------|
 * The user, having a valid session id (credentials) on SSO domain
 * will automatically be connected on site X, with, at the end, a
 * valid PHP session on domain X (using same session id as the one used
 * on SSO domain).
 * - token can only be used 1 time.
 * - token has a short validity (1 minute)
 * - token can only be used on the Site X domain (using Ajax Origin header)
 * - site X domain is checked out, to be a domain managed by the factory only.
 *
 * 2) user is not yet connected
 *
 * Browser             Site X     Site SSO
 *  |  GET /foo (ano.)    |           |
 *  |-------------------->|           |
 *  |   foo + sso js      |           |
 *  |<--------------------|           |
 *  | Ajax /sso/check (no creds)      |
 *  |-------------------------------->|
 *  |     refusal                     |
 *  |<--------------------------------|
 *  | (main anonymous page is unaltered)
 *  |
 *   \--> TODO: login link/page should redirect to master domain
 *   \--> TODO: login link should first send an ajax query to /sso/check
 *                    to check that the user been recently connected
 *  TODO: Safari may have problems with the Vary: Cookie on the /sso/check refusal
 *        (caching the refusal). One solution is adding random on the ajax check
 *        (like the usso timestamp) and ignoring this query string argument on
 *        the reverse proxy cache side (to store only 1 version for all anon.)
 *  TODO: remove the js retry loop?
 */

use MakinaCorpus\Ucms\Site\Site;

/**
 * Implements hook_menu().
 */
function ucms_sso_menu() {
  $items = [];

  $items['sso/goto/%ucms_site'] = [
    'page callback'     => 'ucms_sso_callback_goto',
    'page arguments'    => [2],
    'access callback'   => 'ucms_site_menu_access_view',
    'access arguments'  => [2],
    'type'              => MENU_CALLBACK,
  ];
  $items['sso/check'] = [
    'page callback'     => 'ucms_sso_callback_check',
    'access callback'   => true,
    'type'              => MENU_CALLBACK,
  ];
  $items['sso/login'] = [
    'page callback'     => 'ucms_sso_callback_login',
    'access callback'   => true,
    'type'              => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_menu_site_status_alter().
 */
function ucms_sso_menu_site_status_alter(&$menu_site_status, $path) {
  if (
    MENU_SITE_ONLINE === $menu_site_status &&
    ucms_site_manager()->hasContext() &&
    ucms_site_manager()->getContext()->isPublic()
  ) {
    $path = explode('/', current_path());
    if ('user' === $path[0] && (1 === count($path) || in_array($path[1], ['login', 'logout', 'password', 'register']))) {
      $menu_site_status = MENU_NOT_FOUND;
    }
  }
}

/**
 * Get default URL scheme. Later will always be 'https'.
 */
function ucms_sso_scheme_get() {
  // @todo only https later
  return $GLOBALS['is_https'] ? 'https' : 'http';
}

/**
 * Tells if the current site is master.
 *
 * @return boolean
 */
function ucms_sso_is_master() {
  return !ucms_site_manager()->getContext() && !drupal_is_cli() && $_SERVER['HTTP_HOST'] === variable_get('ucms_site_master_hostname');
}

/**
 * Get a valid HTTP Origin header if it matches an existing site.
 *
 * @return boolean
 */
function ucms_sso_origin_get() {
  if (!empty($_SERVER['HTTP_ORIGIN'])) {
    $manager = ucms_site_manager();
    $site = $manager->getStorage()->findByHostname($_SERVER['HTTP_ORIGIN']);
    if ($site && $manager->getAccess()->userCanView(\Drupal::currentUser(), $site)) {
      return $site->http_host;
    }
  }
}

/**
 * Implements hook_init().
 */
function ucms_sso_init() {
  if (ucms_sso_is_master()) {
    if ($origin = ucms_sso_origin_get()) {
      // we had an origin in the request query, should not happen with images
      // or classical pages so we can be quite sure this was an ajax request.
      // We need to allow modern browsers to send cookies on theses ajax cross
      // domain requests.
      // Note that Access-Control-Allow-Origin: * would not work with
      // credentials, so we also need to send a domain specific authorization.
      // The ucms_sso_origin_get() made the check about validity of this origin.
      drupal_add_http_header('Access-Control-Allow-Origin', ucms_sso_scheme_get() . '://' . $origin);
      drupal_add_http_header('Access-Control-Allow-Credentials', 'true');
      drupal_add_http_header('Access-Control-Allow-Headers', 'Accept, Content-Type');
      drupal_add_http_header('Access-Control-Allow-Methods', 'OPTIONS, GET, POST');

      // This response now contains per-origin values, so a cache_page MUST NOT cache
      // the response (but you may still cache it anyway if you want in varnish
      // for anonymous users, if the cache key is per-domain-used-in-origin, all anon
      // user will have the same rejection status response.
      drupal_page_is_cacheable(FALSE);
    }
  } else {
    // If there is no origin in the HTTP headers, this means we are building
    // a full web page, then we need to add this JS.
    if (!user_is_logged_in() && ($data = ucms_sso_js())) {
      drupal_add_js($data, ['type' => 'inline', 'scope' => 'header']);
    }
  }
}

/**
 * Write token.
 *
 * @param string $origin
 *
 * @return string
 *   Valid URL for login into the site.
 */
function ucms_sso_write_token($origin, $destination = null) {

  // Generate one-time-token for the user, bind to the origin and ip adress
  // the token also depends on the current session identifier.
  $record = [
    'ip'        => ip_address(),
    'origin'    => $origin,
    'session'   => session_id(),
    'validity'  => REQUEST_TIME + 60,
  ];

  $token = drupal_get_token($record['ip'] . $record['origin'] . $record['session'] . $record['validity']);

  cache_set($origin .':'. $token, $record, 'cache_sso', $record['validity']);

  $query = ['s' => $token];
  if ($destination) {
    $query['destination'] = $destination;
  } else if(isset($_GET['destination'])) {
    // Reuse destination that was given to us through the whole process, since
    // it's probably where the user really wants to go in the end.
    $query['destination'] = $_GET['destination'];
  }

  if (!empty($_GET['form_redirect'])) {
    $query['form_redirect'] = $_GET['form_redirect'];
  }

  return url(ucms_sso_scheme_get() . '://' . $origin . '/sso/login/', ['query' => $query, 'absolute' => true]);
}

/**
 * Goto site forcing user to log in.
 */
function ucms_sso_callback_goto(Site $site) {
  $url = ucms_sso_write_token($site->http_host);
  // Thanks, we used you, now go.
  unset($_GET['destination']);
  drupal_goto($url);
}

/**
 * (Not really an) SSO callback.
 */
function ucms_sso_callback_check() {

  if (!$origin = ucms_sso_origin_get()) {
    return MENU_ACCESS_DENIED;
  }

  if (!user_is_logged_in()) {
    // we use a cacheable json response, has all really anonymous users
    // will end up there and this can be easily managed by the reverse
    // proxy cache this will be a 200 and not a 403, better chances of
    //  caching.
    // With cache_page activated we have a cache duration and the
    // Vary: Cookie header.
    // Note that we had an drupal_page_is_cacheable(FALSE); before, so the drupal cache
    // will not cache it, because the HTTP response contains 1 Access-Control-Allow-Origin
    // header which depends on the origin of the query, only Varnish can cache this anon
    // response using the Origin header as a cache key, not Drupal page cache
    return drupal_json_output(['status' => 0]);
  }

  // User 42 is logged on site A (master).
  // User 42 goes on site B (slave).
  // Site B does an AJAX request on A (this callback).
  //  - Token exists: it returns OK, then redirect the client on itself
  //    with session id as token on site B (the next callback).
  //  - Token is wrong: it returns NO, a JavaScript cookie is set and it
  //    prevents the user from loggin in for a few minutes.

  return drupal_json_output(['status' => 1, 'uri' => ucms_sso_write_token($origin)]);
}

/**
 * (Not really an) SSO callback.
 */
function ucms_sso_callback_login() {

  if (empty($_GET['s'])) {
    return MENU_ACCESS_DENIED;
  }

  $token = $_GET['s'];

  if (!preg_match('/^[a-zA-Z0-9_-]+$/', $token)) {
    return MENU_ACCESS_DENIED;
  }

  // retrieve stored temporary token storage
  $domain = $_SERVER['HTTP_HOST'];
  $cid    = $domain .':'. $token;

  $path = '';
  $options = [];
  // Ugly tricks to avoid destination parameter conflict.
  // @see MakinaCorpus\Ucms\Contrib\Form\NodeAddToSite::submitForm
  if (!empty($_GET['destination']) && !empty($_GET['form_redirect'])) {
    $path = $_GET['destination'];
    $options['query']['destination'] = $_GET['form_redirect'];
    // © Meurs mais meurs en brillant
    // © Ils sont morts, alléluia
    unset($_GET['destination']);
  }

  if (user_is_logged_in()) {
    // User is logged in, attempt token removal and exit.
    cache_clear_all($cid, 'cache_sso');
    drupal_goto($path, $options);
  }

  $entry = cache_get($cid, 'cache_sso');
  if (!$entry) {
    return MENU_ACCESS_DENIED;
  }

  $record = $entry->data;

  // ALWAYS invalidate this token for future use that's a ONE TIME thing.
  cache_clear_all($cid, 'cache_sso');

  // Check that this record was for this site, this IP, and with a good validity.
  if (ip_address() !== $record['ip'] || $domain != $record['origin'] || $record['validity'] < REQUEST_TIME) {
    return MENU_ACCESS_DENIED;
  }

  $sessionId = $record['session'];

  // Set the new session cookie on this domain, which is in fact the same as the master domain session
  setcookie(session_name(), false);
  $params = session_get_cookie_params();
  $expire = $params['lifetime'] ? REQUEST_TIME + $params['lifetime'] : 0;
  setcookie(session_name(), $sessionId, $expire, $params['path'], $params['domain'], $params['secure'], $params['httponly']);
  // Leave the user to the page he sould be.
  drupal_goto($path, $options);
}

/**
 * Get the SSO javascript.
 */
function ucms_sso_js() {

  $masterHostname = variable_get('ucms_site_master_hostname');

  if (!$masterHostname) {
    return;
  }

  $master = url(ucms_sso_scheme_get() . '://' . $masterHostname . '/sso/check');

  // This is the packed version, please note that you want to edit the
  // ucms_sso.js instead, then pack it using http://dean.edwards.name/packer/
  // in which case, don't worry about the ${master}, it will be left untouched
  // by the packer.
  return <<<EOT
(function(){"use strict";var d=document;function n(){return Math.floor(Date.now()/1000)}function stop(){d.cookie="usso="+(n()+240)}function may(){var a=d.cookie.match(/usso=([\d]+)(;|$)/);return!a||a[1]<n()}if(may()){var x=new XMLHttpRequest();x.open("GET","${master}");x.withCredentials=true;x.setRequestHeader("Accept","application/json");x.onerror=function(){stop()};x.onload=function(){try{var d=JSON.parse(this.responseText);if(d.status&&d.uri){window.location.href=d.uri+"&destination="+window.location.href}stop()}catch(e){stop()}};x.send()}}());
EOT;
}
